export const testFilms = [
    { title: "Parix, Texas", director: "Wim Wenders", hasWatched: true },
    { title: "Kill Bill Vol. 1", director: "Quentin Tarentino", hasWatched: false },
    { title: "Goodfellas", director: "Martin Scorcese" },
    { title: "The Doors", director: "Oliver Stone" },
    { title: "Avengers: End Game", director: "Blah Blah" },
    { title: "You've Got Mail", director: "Blah Blah" },
    { title: "Parix, Texas", director: "Wim Wenders" },
    { title: "Kill Bill Vol. 1", director: "Quentin Tarentino" },
    { title: "Goodfellas", director: "Martin Scorcese" },
    { title: "The Doors", director: "Oliver Stone" },
    { title: "Avengers: End Game", director: "Blah Blah" },
    { title: "You've Got Mail", director: "Blah Blah" },
    { title: "Parix, Texas", director: "Wim Wenders" },
    { title: "Kill Bill Vol. 1", director: "Quentin Tarentino" },
    { title: "Goodfellas", director: "Martin Scorcese" },
    { title: "The Doors", director: "Oliver Stone" },
    { title: "Avengers: End Game", director: "Blah Blah" },
    { title: "You've Got Mail", director: "Blah Blah" },
    { title: "Parix, Texas", director: "Wim Wenders" },
    { title: "Kill Bill Vol. 1", director: "Quentin Tarentino" },
    { title: "Goodfellas", director: "Martin Scorcese" },
    { title: "The Doors", director: "Oliver Stone" },
    { title: "Avengers: End Game", director: "Blah Blah" },
    { title: "You've Got Mail", director: "Blah Blah" },
]